name: CI Terminal Icons

on:
  push:
    branches:
      - "main"
    paths:
      - "terminal/**"
      - ".github/workflows/validate-terminal-icons.yml"
  pull_request:
    branches:
      - "main"
    paths:
      - "terminal/**"
      - ".github/workflows/validate-terminal-icons.yml"

jobs:
  check_terminal_profile_icons:
    name: Check That Terminal Profile Icons Exists
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check if expected icons in the repos exists
        shell: pwsh
        run: |
          $terminalSettingsContent = ConvertFrom-Json -InputObject (Get-Content -Path '.\terminal\settings.json' -Raw);
          $profilesIconsInThisRepo = $terminalSettingsContent.profiles.list.icon | Where-Object {
            $_ -like 'http*'
          }

          if ( $profilesIconsInThisRepo.Length -eq 0) {
            Write-Host 'No icons to check';
            exit 0;
          }

          $inError = $false
          $profilesIconsInThisRepo | ForEach-Object {
            $result = Invoke-WebRequest -Method Get -Uri $_ -SkipHttpErrorCheck

            if ($result.StatusCode -ne 200) {
              Write-Host "Icon at '$($_)' not found";
              $inError = $true
            }
          }

          if ($inError) {
            exit 1
          }
